version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    # Mapear el puerto de la máquina host al contenedor
    ports:
      - "${PORT}:${PORT}"
    # Cargar variables de entorno desde .env
    env_file:
      - .env
    # NODE_ENV lo tomamos del Makefile o de la shell (default: development)
    environment:
      - NODE_ENV=${NODE_ENV}
    # Reiniciar a menos que se pare manualmente
    restart: unless-stopped

# Se puede agregar un servicio de Mongo local si se desea usar en lugar de Atlas:
#  mongo:
#    image: mongo:6.0
#    container_name: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/db
#
#volumes:
#  mongo_data: