version: '3.8'

services:
  api:
    container_name: chat-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    # Mapear el puerto de la máquina host al contenedor
    ports:
      - "${PORT}:${PORT}"
    # Cargar variables de entorno desde .env
    env_file:
      - .env
    # NODE_ENV lo tomamos del Makefile o de la shell (default: development)
    environment:
      - NODE_ENV=${NODE_ENV}
    # Reiniciar a menos que se pare manualmente
    restart: unless-stopped

  frontend:
    container_name: chat-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped